### ISSUE TITLE
AssemblyLoader: Exception loading 'KolonyTools'

### ISSUE THREAD

**Issue by RealKolago** [BobPalmer/Kolonization#8]
AssemblyLoader: Exception loading 'KolonyTools': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)

  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 

  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

Additional information about this exception:

 System.TypeLoadException: Could not load type 'KolonyTools.MKSLlocal' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'KolonyTools.MKSLogisticsMasterView' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'Kolonization.KolonizationMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'PlanetaryLogistics.PlanetaryLogisticsMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'KolonyTools.StationManager' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'Kolonization.KolonizationMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'Kolonization.KolonizationMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'Kolonization.KolonizationMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'Kolonization.KolonizationMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'PlanetaryLogistics.PlanetaryLogisticsMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'PlanetaryLogistics.PlanetaryLogisticsMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type 'PlanetaryLogistics.PlanetaryLogisticsMonitor' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass6' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClassd' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass15' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass18' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass6' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

 System.TypeLoadException: Could not load type '<>c__DisplayClass6' from assembly 'KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Full Log: https://www.dropbox.com/s/uihtw6iz75d019m/output_log12.zip?dl=0

**Comment by BobPalmer** [comment]
Need a lot more context - i.e. what behavior are you seeing in game?

**Comment by RealKolago** [comment]
Game loads fine. Except of KolonyTools related functions do not work all seems ok.
Some exception with MechJeb:

MechJeb moduleRegistry creation threw an exception in LoadComputerModules loading KolonyTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.

  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)

  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 

  at MuMech.MechJebCore.LoadComputerModules () [0x00000] in <filename unknown>:0

**Comment by RealKolago** [comment]
After last update the exception is gone.
